/* eslint-disable */
// Generated by 'unplugin-auto-mixcode'

declare module "virtual:mixcode/pages/index" {
  import type { RouteRecordRaw } from "vue-router";
  const routes: RouteRecordRaw[];
  export default routes;
}

declare module "virtual:mixcode/dialog/use" {
  export type ComponentProps<T> =
    & Record<string, unknown>
    & (
      T extends new (...args: any) => { $props: infer Props } ? Props
        : T extends (props: infer Props, ...args: any) => any ? Props
        : T extends (...args: any) => { props: infer Props } ? Props
        : T extends new (...args: any) => any ? {}
        : T extends (...args: any) => any ? {}
        : T // IntrinsicElement
    );
}

declare module "virtual:mixcode/dialog/use$HelloDialog" {
  import type { MaybeRef } from "@vueuse/core";
  import type { TeleportProps, TransitionProps } from "vue";
  import type { GlobalComponents } from "@vue/runtime-core";
  import type { ComponentProps } from "virtual:mixcode/dialog/use";
  type Props = Omit<
    ComponentProps<GlobalComponents["HelloDialog"]>,
    "class" | "style" | "key" | "ref" | "ref_for" | "ref_key" | `on${string}`
  >;
  export default function (
    teleportProps: MaybeRef<Partial<TeleportProps>> = {},
    transitionProps: MaybeRef<TransitionProps> = {},
  ): (props: Props) => Promise<Props | undefined>
}
