/* eslint-disable */
// Generated by 'unplugin-auto-mixcode'

declare module "virtual:mixcode/pages/index" {
  declare module "virtual:mixcode/pages/index" {
    import type { RouteRecordRaw } from "vue-router";
    const routes: RouteRecordRaw[]
    export default routes
  }
}
