/* eslint-disable */
// Generated by 'unplugin-auto-mixcode'

declare module "virtual:mixcode/dialog/use$HelloWorldDialog" {
  import { OpenPromisifyDialog, TeleportProps } from "@mixcode/glue-react";
  export default function (
    teleportProps?: TeleportProps,
  ): OpenPromisifyDialog<typeof HelloWorldDialog>;
}

declare module "virtual:mixcode/dialog/use$ExampleDialog" {
  import { OpenPromisifyDialog, TeleportProps } from "@mixcode/glue-react";
  export default function (
    teleportProps?: TeleportProps,
  ): OpenPromisifyDialog<typeof ExampleDialog>;
}

declare module "virtual:mixcode/pages/index" {
  import type { RouteObject } from "react-router-dom";
  const routes: RouteObject[];
  export default routes;
}
