/* eslint-disable */
// Generated by 'unplugin-auto-mixcode'

declare module "virtual:mixcode/dialog/useExampleDialog" {
  import { OpenPromisifyDialog, TeleportProps } from "@mixcode/glue-react";
  export default function (
    teleportProps?: TeleportProps,
  ): OpenPromisifyDialog<typeof ExampleDialog>;
}

declare module "virtual:mixcode/dialog/useHelloWorldDialog" {
  import { OpenPromisifyDialog, TeleportProps } from "@mixcode/glue-react";
  export default function (
    teleportProps?: TeleportProps,
  ): OpenPromisifyDialog<typeof HelloWorldDialog>;
}